apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-nope
  namespace: argocd
  labels:
    name: au
spec:
  destination:
    namespace: dev-app
    name: dev
  project: default
  source:
    path: sample-app/
    repoURL: https://github.com/kurtburak/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true